name: movie_app_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.2.3
  tmdb_api: ^2.2.0
  google_fonts: ^6.3.0
  flutter_stripe: ^11.5.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0  # Added Firestore
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  animate_do: ^4.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
