// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEPvPmAZWkg0ow2csBMl8KRim1kPxZVU',
    appId: '1:204903377132:web:12fb8aca5d6327591b5dc9',
    messagingSenderId: '204903377132',
    projectId: 'movieticket-923bd',
    authDomain: 'movieticket-923bd.firebaseapp.com',
    storageBucket: 'movieticket-923bd.appspot.com',
    measurementId: 'G-EW49MNCFRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9m5T_Q_IW7Phm8yu7vwFueR-0ye21RS8',
    appId: '1:204903377132:android:310826b15e8416c61b5dc9',
    messagingSenderId: '204903377132',
    projectId: 'movieticket-923bd',
    storageBucket: 'movieticket-923bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5WNXvPLfBfzAl2zbapil03_SEeAemxQY',
    appId: '1:204903377132:ios:e8f65fcffeeb3e741b5dc9',
    messagingSenderId: '204903377132',
    projectId: 'movieticket-923bd',
    storageBucket: 'movieticket-923bd.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5WNXvPLfBfzAl2zbapil03_SEeAemxQY',
    appId: '1:204903377132:ios:e8f65fcffeeb3e741b5dc9',
    messagingSenderId: '204903377132',
    projectId: 'movieticket-923bd',
    storageBucket: 'movieticket-923bd.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALEPvPmAZWkg0ow2csBMl8KRim1kPxZVU',
    appId: '1:204903377132:web:13904389c48c86601b5dc9',
    messagingSenderId: '204903377132',
    projectId: 'movieticket-923bd',
    authDomain: 'movieticket-923bd.firebaseapp.com',
    storageBucket: 'movieticket-923bd.appspot.com',
    measurementId: 'G-5TQY0ZXGN8',
  );
}
